#!/usr/bin/env node
// Stamp every shipped metadata source from the single source of truth in
// /package.json. The release pipeline invokes this before any other build so
// every published artifact advertises the same version.
//
// Sources updated:
//   - /package.json
//   - /package-lock.json (root package version only)
//   - /desktop-client-tauri/package.json
//   - /desktop-client-tauri/package-lock.json
//   - /desktop-client-tauri/src-tauri/Cargo.toml
//   - /desktop-client-tauri/src-tauri/tauri.conf.json
//   - /mobile/package.json
//   - /mobile/package-lock.json
//   - /mobile/android/app/build.gradle (versionName, versionCode)
//   - /mobile/ios/App/App/Info.plist (CFBundleShortVersionString, CFBundleVersion)
//   - /docs/openapi.json (info.version)
//   - /packaging/aur/gulden-client/PKGBUILD (pkgver; source URL; sha256sums reset)
//   - /packaging/aur/gulden-client/.SRCINFO (regenerated by build-aur.sh)
//
// This script is idempotent: invoking it twice with the same version produces
// no diff. The script only modifies files when the new value differs from the
// existing one, so a stale or unrelated edit is left alone.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

function readJSON(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function writeJSON(file, value) {
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n');
}

function replaceInFile(file, replacements) {
  const original = fs.readFileSync(file, 'utf8');
  let next = original;
  let changed = false;
  for (const { pattern, replacement } of replacements) {
    if (typeof pattern === 'string') {
      if (next.includes(pattern)) {
        const after = next.replace(pattern, replacement);
        if (after !== next) {
          next = after;
          changed = true;
        }
      } else {
        throw new Error(`sync-version: expected substring not found in ${file}: ${pattern}`);
      }
    } else {
      if (!pattern.test(next)) {
        throw new Error(`sync-version: regex ${pattern} did not match in ${file}`);
      }
      const after = next.replace(pattern, replacement);
      if (after !== next) {
        next = after;
        changed = true;
      }
    }
  }
  if (changed) fs.writeFileSync(file, next);
  return changed;
}

function versionCodeFor(version) {
  const [maj, min, pat] = version.split('.').map((n) => Number.parseInt(n, 10));
  if ([maj, min].some((n) => !Number.isFinite(n))) {
    throw new Error(`sync-version: invalid version "${version}"`);
  }
  const patch = Number.isFinite(pat) ? pat : 0;
  return maj * 10000 + min * 100 + patch;
}

function assertSemver(version) {
  if (!/^\d+\.\d+\.\d+(?:[-+].+)?$/.test(version)) {
    throw new Error(`sync-version: "${version}" is not semver`);
  }
}

const targets = [];

function planPackage(file) {
  const json = readJSON(file);
  const before = json.version;
  json.version = version;
  writeJSON(file, json);
  targets.push({ file, before, after: version, kind: 'package-version' });
}

function planLockPackage(file) {
  // The top-level package lock only carries the package name + version; the
  // exact shape of node_modules is regenerated by `npm install`. We only need
  // to keep the root marker in sync.
  const text = fs.readFileSync(file, 'utf8');
  const json = JSON.parse(text);
  const before = json.packages?.['']?.version ?? json.version;
  if (json.version) json.version = version;
  if (json.packages?.['']) json.packages[''].version = version;
  const after = json.packages?.['']?.version ?? json.version;
  if (before !== after) {
    writeJSON(file, json);
    targets.push({ file, before, after, kind: 'lockfile' });
  }
}

function planCargoToml(file) {
  const before = fs.readFileSync(file, 'utf8');
  const after = before.replace(
    /^version\s*=\s*"\d+\.\d+\.\d+(?:-[^"]+)?"/m,
    `version = "${version}"`,
  );
  if (before !== after) {
    fs.writeFileSync(file, after);
    targets.push({ file, kind: 'cargo-toml' });
  }
}

function planTauriConf(file) {
  const before = fs.readFileSync(file, 'utf8');
  const after = before.replace(
    /"version"\s*:\s*"\d+\.\d+\.\d+(?:-[^"]+)?"/,
    `"version": "${version}"`,
  );
  if (before !== after) {
    fs.writeFileSync(file, after);
    targets.push({ file, kind: 'tauri-conf' });
  }
}

function planAndroidBuild(file) {
  const code = versionCodeFor(version);
  replaceInFile(file, [
    { pattern: /^(\s*)versionCode\s+\d+/m, replacement: `$1versionCode ${code}` },
    { pattern: /^(\s*)versionName\s+"[^"]+"/m, replacement: `$1versionName "${version}"` },
  ]);
  targets.push({ file, kind: 'android-build' });
}

function planIOSInfoPlist(file) {
  // CFBundleVersion carries the numeric build; CFBundleShortVersionString is
  // the human-readable "marketing" version. Both are normally interpolated
  // from Xcode build settings — we stamp the Xcode project as well.
  const code = versionCodeFor(version);
  replaceInFile(file, [
    {
      pattern: /<key>CFBundleShortVersionString<\/key>\s*<string>[^<]+<\/string>/,
      replacement: `<key>CFBundleShortVersionString</key>\n\t<string>${version}</string>`,
    },
    {
      pattern: /<key>CFBundleVersion<\/key>\s*<string>[^<]+<\/string>/,
      replacement: `<key>CFBundleVersion</key>\n\t<string>${code}</string>`,
    },
  ]);
  targets.push({ file, kind: 'ios-plist' });
}

function planXcodeProject(file) {
  const code = versionCodeFor(version);
  replaceInFile(file, [
    { pattern: /MARKETING_VERSION\s*=\s*[^;]+;/g, replacement: `MARKETING_VERSION = ${version};` },
    {
      pattern: /CURRENT_PROJECT_VERSION\s*=\s*[^;]+;/g,
      replacement: `CURRENT_PROJECT_VERSION = ${code};`,
    },
  ]);
  targets.push({ file, kind: 'xcode-project' });
}

function planOpenAPI(file) {
  const before = fs.readFileSync(file, 'utf8');
  const after = before.replace(
    /"version"\s*:\s*"\d+\.\d+\.\d+(?:-[^"]+)?"/,
    `"version": "${version}"`,
  );
  if (before !== after) {
    fs.writeFileSync(file, after);
    targets.push({ file, kind: 'openapi' });
  }
}

function planPKGBUILD(file) {
  // PKGBUILD's source line and sha256sums change between releases, so
  // build-aur.sh keeps them in sync. Here we only stamp pkgver; the
  // release-time tool rewrites the URL and checksum just-in-time.
  replaceInFile(file, [{ pattern: /^pkgver=.*/m, replacement: `pkgver=${version}` }]);
  targets.push({ file, kind: 'pkgbuild' });
}

function planChangelog(file) {
  // We do not rewrite the changelog here (humans own those entries). We just
  // confirm the most recent heading carries the version we are publishing.
  // IMPORTANT: this check uses the BEFORE value, so the test must update the
  // changelog in the staging copy BEFORE running the script.
  const text = fs.readFileSync(file, 'utf8');
  const match = text.match(/^##\s*\[(\d+\.\d+\.\d+(?:-[^]]+)?)\][^\n]*$/m);
  if (!match) {
    throw new Error(`sync-version: no ## [<version>] entry at the top of ${file}`);
  }
  if (match[1] !== version) {
    throw new Error(
      `sync-version: top of ${file} is "${match[1]}" but package.json is "${version}". ` +
        'Update CHANGELOG.md before running this script.',
    );
  }
  targets.push({ file, kind: 'changelog' });
}

const argVersion = process.argv[2];
if (!argVersion) {
  console.error('usage: node scripts/sync-version.mjs <version> [repo-root]');
  process.exit(2);
}
assertSemver(argVersion);
const version = argVersion;
const baseRoot = process.argv[3] ? path.resolve(process.argv[3]) : root;

// Validate changelog lead BEFORE writing anything. Otherwise a release job
// would leave the tree half-updated if a contributor forgot to add a
// CHANGELOG.md entry for the new version.
const changelogFile = path.join(baseRoot, 'CHANGELOG.md');
planChangelog(changelogFile);

const rootPkg = readJSON(path.join(baseRoot, 'package.json'));
const beforeRoot = rootPkg.version;
rootPkg.version = version;
writeJSON(path.join(baseRoot, 'package.json'), rootPkg);
targets.push({ file: 'package.json', before: beforeRoot, after: version, kind: 'package-version' });

planLockPackage(path.join(baseRoot, 'package-lock.json'));
planPackage(path.join(baseRoot, 'desktop-client-tauri', 'package.json'));
planLockPackage(path.join(baseRoot, 'desktop-client-tauri', 'package-lock.json'));
planCargoToml(path.join(baseRoot, 'desktop-client-tauri', 'src-tauri', 'Cargo.toml'));
planTauriConf(path.join(baseRoot, 'desktop-client-tauri', 'src-tauri', 'tauri.conf.json'));
planPackage(path.join(baseRoot, 'mobile', 'package.json'));
planLockPackage(path.join(baseRoot, 'mobile', 'package-lock.json'));
planAndroidBuild(path.join(baseRoot, 'mobile', 'android', 'app', 'build.gradle'));
planIOSInfoPlist(path.join(baseRoot, 'mobile', 'ios', 'App', 'App', 'Info.plist'));
planXcodeProject(path.join(baseRoot, 'mobile', 'ios', 'App', 'App.xcodeproj', 'project.pbxproj'));
planOpenAPI(path.join(baseRoot, 'docs', 'openapi.json'));
planPKGBUILD(path.join(baseRoot, 'packaging', 'aur', 'gulden-client', 'PKGBUILD'));

let touched = 0;
for (const t of targets) if (t.kind !== 'changelog') touched++;
console.log(`sync-version: stamped ${touched} file(s) to ${version}`);
for (const t of targets) console.log(`  - ${t.kind.padEnd(18)} ${t.file}`);
