#!/bin/bash
# 'remove' keeps /var/lib/gulden (your data!). Only 'purge' deletes it.
if [ "$1" = "purge" ]; then
  rm -rf /var/lib/gulden
  deb-systemd-helper purge gulden.service || true
  deb-systemd-helper unmask gulden.service || true
fi
